"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert("Prices", [
      {
        service_id: 1,
        title: "베이식",
        price: "9500원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 1,
        title: "스탠다드",
        price: "13500원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 1,
        title: "프리미엄",
        price: "14500원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 2,
        title: "베이식",
        price: "7900원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 2,
        title: "프리미엄",
        price: "12900원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 3,
        title: "프리미엄",
        price: "9500원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 4,
        title: "베이식",
        price: "7900원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 4,
        title: "스탠다드",
        price: "10900원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 4,
        title: "프리미엄",
        price: "13900원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 5,
        title: "베이식",
        price: "7900원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 5,
        title: "스탠다드",
        price: "10900원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 5,
        title: "프리미엄",
        price: "13900원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 6,
        title: "베이식",
        price: "9900원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 6,
        title: "프리미엄",
        price: "14900원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 7,
        title: "기본",
        price: "9900원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 8,
        title: "기본",
        price: "6500원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 9,
        title: "기본",
        price: "9900원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 10,
        title: "기본",
        price: "4900원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 11,
        title: "기본",
        price: "4900원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 12,
        title: "스탠다드",
        price: "5500원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        service_id: 12,
        title: "프리미엄",
        price: "7700원",
        message: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
